# Deploy Next.js app to GitHub Pages for production and test branches
name: Deploy Pages (prod + test)

on:
  push:
    branches: [main, test]

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build Next.js app (PROD)
        if: github.ref_name == 'main'
        run: npm run build
        env:
          NEXT_PUBLIC_BASE_PATH: '/qr'

      - name: Build Next.js app (TEST)
        if: github.ref_name == 'test'
        run: npm run build
        env:
          NEXT_PUBLIC_BASE_PATH: '/qr/test'

      - name: Add .nojekyll file
        run: touch ./out/.nojekyll

      # PROD → корень gh-pages
      - name: Deploy PROD to gh-pages root
        if: github.ref_name == 'main'
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: ./out
          destination_dir: .
          keep_files: false
          enable_jekyll: false

      # TEST → gh-pages/test
      - name: Deploy TEST to gh-pages/test
        if: github.ref_name == 'test'
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: ./out
          destination_dir: test
          keep_files: true
          enable_jekyll: false
