name: tests

on:
  push:
    branches:
      - test
      - main
  pull_request:

jobs:
  unit-tests:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run typecheck and unit tests
        run: npm test

  playwright:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Install Playwright browsers
        run: npx playwright install --with-deps

      - name: Build Next.js app
        run: npm run build
        env:
          BASE_PATH: ''

      - name: Run Playwright tests
        run: npm run test:e2e
        env:
          APP_URL: ${{ secrets.APP_URL }}
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          TEST_INITDATA: ${{ secrets.TEST_INITDATA }}

      - name: Setup Python for QR validation
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: Install zbar library (required by pyzbar)
        run: sudo apt-get update && sudo apt-get install -y libzbar0

      - name: Install Python dependencies
        run: pip install -r requirements-test.txt

      - name: Validate QR codes are scannable
        run: python -m pytest tests/testValidQrScrenshots.py -v

      - name: Upload QR Preview Screenshots
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: qr-preview-screenshots
          path: screenshots/
          retention-days: 30

      - name: Upload Playwright report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-report
          path: playwright-report
          retention-days: 30

      - name: Upload test artifacts
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: test-artifacts
          path: |
            test-results
            **/*.mp4
            **/*.webm
            **/*.zip
          retention-days: 30
